### ISSUE TITLE
Error in scale/downscale.yml

### ISSUE THREAD

**Issue by jromers** [oracle/ocne-deploy-tool#1]
The olcnectl module update command has static names for environment and cluster, this need to be changed in:

From:
--environment-name myenvironment \
--name mycluster \
To:
--environment-name {{ ocne_environment }} \
--name {{ ocne_k8s }} \

**Comment by krajendra95** [comment]
Fixed in commit 05560c8a5fa01a1449673e326aae6a530c85e13d
