### ISSUE TITLE
Deploy failed with non-root user

### ISSUE THREAD

**Issue by krajendra95** [oracle/ocne-deploy-tool#3]
Running the tool with non-root user such as opc fails.
Example :
[opc@server ocne-deploy-tool]$ ./ocne_olvm --run-playbook
==================== OCNE Deployment tool for OLVM ====================
========== Beginning the Deployment Process ==========

Do you want to save current VM and OCNE cluster configuration settings and encrypted passwords? {y/N):n
Vault password:

PLAY [olvm] *********************************************************************************************************************************************************************************************

TASK [Verify wget availability] *************************************************************************************************************************************************************************
fatal: [server.example.com]: FAILED! => {"msg": "Missing sudo password"}

PLAY RECAP **********************************************************************************************************************************************************************************************
server.example.com         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by shishirhegde16** [comment]
This is now fixed via 0e6306c2c89af618ba23fa74bf64fb3065968b8d
